VIA_ENABLE = no
VIAL_ENABLE = yes
VIALRGB_ENABLE = no
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
CONSOLE_ENABLE = no
RGB_MATRIX_ENABLE = no
COMBO_ENABLE = no
TAP_DANCE_ENABLE = no

